export {
    DEFAULT_FREEFORM_LAYOUT_CONFIG,
    FREEFORM_COLLAPSED_HEIGHT,
    bringViewPlacementToFront,
    bringViewPlacementsToFront,
    calculateFreeformCanvasHeight,
    createDefaultViewPlacement,
    createDefaultViewPlacements,
    getDefaultFreeformItemSize,
    filterViewPlacementsForLayout,
    getFreeformVisualHeight,
    moveViewPlacement,
    normalizeFreeformLayoutConfig,
    normalizeViewPlacementZIndices,
    normalizeViewPlacement,
    removeViewPlacement,
    resizeViewPlacement,
    resolveViewPlacements,
    snapFreeformValue,
} from './freeformLayout';
export type { FreeformItemSize } from './freeformLayout';
