window.DOC_SEARCH_INDEX = [
  {
    "title": "首页仪表盘",
    "url": "index.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "首页仪表盘"
    ],
    "summary": "把 Think OS 插件的定位、需求、功能、代码和发布状态放到一个入口里。"
  },
  {
    "title": "项目总览",
    "url": "00-基础入口/00-项目驾驶舱/项目总览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "项目总览"
    ],
    "summary": "用一页说明插件是什么、处于什么阶段、主要文档入口在哪里。"
  },
  {
    "title": "快速开始",
    "url": "00-基础入口/00-项目驾驶舱/快速开始.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "快速开始",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "给未来的自己一个最短路径：如何看项目、跑项目、改项目。"
  },
  {
    "title": "插件定位",
    "url": "00-基础入口/01-概念与边界/插件定位.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件定位",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "固定插件解决的问题、边界和优先级，避免功能越做越散。"
  },
  {
    "title": "功能地图",
    "url": "00-基础入口/01-概念与边界/功能地图.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能地图",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "从用户视角列出插件功能，而不是从文件夹视角列代码。"
  },
  {
    "title": "当前状态",
    "url": "00-基础入口/00-项目驾驶舱/当前状态.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "当前状态",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "记录项目当前处境，尤其是哪些入口是正式的，哪些资料已经准备弃用。"
  },
  {
    "title": "术语表",
    "url": "00-基础入口/01-概念与边界/术语表.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "术语表",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "把项目里反复出现的英文、Obsidian 概念和内部命名固定下来。"
  },
  {
    "title": "常见问题",
    "url": "00-基础入口/01-概念与边界/常见问题.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "常见问题",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "把反复会问的问题集中回答，降低未来查找成本。"
  },
  {
    "title": "迁移文档索引",
    "url": "00-基础入口/02-迁移与旧资料/迁移文档索引.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移文档索引",
      "需求"
    ],
    "summary": "查看 docs/html 旧资料被迁移到了哪些新主题下。"
  },
  {
    "title": "旧章节总览",
    "url": "00-基础入口/02-迁移与旧资料/旧章节总览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-01-总览.js",
      "platform",
      "share",
      "一、总览",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "旧章节总览",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "结构说明"
  },
  {
    "title": "章节化文档框架",
    "url": "00-基础入口/02-迁移与旧资料/章节化文档框架.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Think OS 开发文档",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/index.html",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "基础入口",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "章节化文档框架",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "Think OS 开发文档Think OS 开发文档总入口只负责引入公共样式、公共脚本，以及按顺序引入各个章节文件。交互说明目录点击后只显示当前章节。在逻辑图区域中：Ctrl + 滚轮：缩放图Shift + 滚轮：左右移动图Think OS 章节化开发文档"
  },
  {
    "title": "需求池",
    "url": "01-项目管理/00-计划与路线/需求池.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "需求池",
      "项目管理"
    ],
    "summary": "所有想法先进入需求池，再决定是否开发、何时开发、如何验收。"
  },
  {
    "title": "版本路线图",
    "url": "01-项目管理/00-计划与路线/版本路线图.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "版本路线图",
      "移动端",
      "输入",
      "需求",
      "项目管理"
    ],
    "summary": "把项目拆成可推进的阶段，避免所有事情同时开工。"
  },
  {
    "title": "开发计划",
    "url": "01-项目管理/00-计划与路线/开发计划.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "开发计划",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "项目管理"
    ],
    "summary": "把下一步开发变成小批次任务，避免一口气重构太多。"
  },
  {
    "title": "问题记录",
    "url": "01-项目管理/01-过程记录/问题记录.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "问题记录",
      "需求",
      "项目管理"
    ],
    "summary": "记录已经遇到或可能反复出现的问题，避免重复踩坑。"
  },
  {
    "title": "技术债",
    "url": "01-项目管理/01-过程记录/技术债.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术债",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "项目管理"
    ],
    "summary": "把“以后再说”的东西记下来，并给它们一个处理优先级。"
  },
  {
    "title": "决策记录",
    "url": "01-项目管理/01-过程记录/决策记录.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "决策记录",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "项目管理"
    ],
    "summary": "记录为什么这样设计，避免以后只看到结果看不到原因。"
  },
  {
    "title": "发布记录",
    "url": "01-项目管理/01-过程记录/发布记录.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "发布记录",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求",
      "项目管理"
    ],
    "summary": "记录每个版本发布了什么、改了什么、有没有风险。"
  },
  {
    "title": "插件深度报告与实施计划",
    "url": "01-项目管理/02-实施计划/插件深度报告与实施计划.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/插件深度报告与实施计划.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "插件深度报告与实施总计划表",
      "插件深度报告与实施计划",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "先做深度报告，再确认核心字段契约，再确认上下文模型，再确认时间领域规则，最后才按 P0 / P1 / P2 节奏改代码；所有实施都必须服从前面确认出的真源。"
  },
  {
    "title": "上下文时间重构计划",
    "url": "01-项目管理/02-实施计划/上下文时间重构计划.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/上下文 时间重构.md",
      "features",
      "platform",
      "share",
      "上下文时间重构计划",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "当前阶段实施总计划表（P0 止痛 / P1 稳定 / P2 重构）",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "对，这个我修正一下：你这个例子是对的：所以更合理的规则是：也就是说，保留：不保留：如果以后真要显示，可以有一个**只读派生状态**：它是算出来的，不是填出来的。下面我把 **P0 止痛 / P1 稳定 / P2 重构** 合成一张总表，并加上你要的："
  },
  {
    "title": "统一输入修改计划",
    "url": "01-项目管理/02-实施计划/统一输入修改计划.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/输入编辑统一计划.md",
      "features",
      "platform",
      "share",
      "一、目标先说清",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "统一输入修改计划",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "可以，下面是 **《统一输入修改计划表 v2（已纳入副作用管理）》**。我按你当前代码结构来排，已经把这些实际位置考虑进去了：先给一句总原则：这次改造不是“优化 quickinput”，而是统一这 4 件事：1. 所有新建 / 修改 / 删除入口"
  },
  {
    "title": "原始计划记录",
    "url": "01-项目管理/02-实施计划/原始计划记录.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/计划.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "原始计划记录",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "计划",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "从旧 docs/html 迁移来的文档，已按新文档结构重新归类。"
  },
  {
    "title": "旧需求台账",
    "url": "01-项目管理/02-实施计划/旧需求台账.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-03-需求台账.js",
      "platform",
      "share",
      "三、需求台账",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "旧需求台账",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "可直接编辑"
  },
  {
    "title": "Batch1 实施报告",
    "url": "01-项目管理/03-实施报告/Batch1实施报告.html",
    "tags": [
      "AI",
      "Batch1 实施报告",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/BATCH1_IMPLEMENTATION_REPORT.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "统一输入改造实施 - 第 1 批落地报告（record 域 / QuickInput create-edit）",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "严格按本批约束落地：这里是**本次实际落地签名**。为了贴合当前代码结构，`prepare*` 落成了**同步接口**，避免给 `QuickInputModal` 引入额外异步装载状态；`submit*` 仍然是异步。1. **QuickInputModal 不再直接 import / 调用 `InputService"
  },
  {
    "title": "Batch2 实施报告",
    "url": "01-项目管理/03-实施报告/Batch2实施报告.html",
    "tags": [
      "AI",
      "Batch2 实施报告",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/BATCH2_IMPLEMENTATION_REPORT.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "统一输入改造 Batch 2 实施报告",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "严格按要求执行：本批目标：把剩余 record 动作统一收口到 `recordInput.usecase`。覆盖的旧链：1. `AiBatchConfirmModal -> InputService.executeTemplate`2. `TimerService.createNewTaskAndStart -> In"
  },
  {
    "title": "QuickInput 主线修改记录",
    "url": "01-项目管理/03-实施报告/QuickInput主线修改记录.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "QuickInput 主线修改记录",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-mainline-change-log.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "当前主线优先处理：任务读取、时间计算、写回保真、保存位置可见与安全迁移。1. 任务内容提取统一到 `extractTaskEditableText()`。2. 任务模板识别增加 guard，避免任务被误判成闪念/block。3. 时间计算支持中文字段与 start/end/duration 别名。"
  },
  {
    "title": "QuickInput 收口状态",
    "url": "01-项目管理/03-实施报告/QuickInput收口状态.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 收口状态",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-closeout-state.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "本轮修改已经进入收口阶段。主链路不建议继续大改。如果本轮手测稳定，下一轮可以考虑：1. 自动迁移保存增加确认弹窗2. 任务 token 级 patch serializer3. block 编辑也完全切到 snapshot4. 删除 legacy 主路径"
  },
  {
    "title": "QuickInput 本轮修改总览",
    "url": "01-项目管理/03-实施报告/QuickInput本轮修改总览.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 本轮修改总览",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-final-change-summary.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "项目管理"
    ],
    "summary": "本轮修改围绕 QuickInput 的任务编辑主链路收口：1. 任务内容完整读取2. 时间字段默认值与联动计算3. 主题字段三分法：根主题 / 叶主题 / 完整路径4. 任务写回保真5. 保存位置实时预览6. 路径变化迁移保存7. partial_success 反馈收口"
  },
  {
    "title": "功能总览",
    "url": "02-功能设计/00-功能全景/功能总览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能总览",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "把插件功能按用户能力组织，而不是按代码目录组织。"
  },
  {
    "title": "用户场景",
    "url": "02-功能设计/01-用户与交互/用户场景.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "用户场景",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "从用户什么时候需要这个插件开始设计，而不是从组件开始设计。"
  },
  {
    "title": "命令设计",
    "url": "02-功能设计/01-用户与交互/命令设计.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "命令设计",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "集中管理插件通过命令面板暴露给用户的动作。"
  },
  {
    "title": "设置项设计",
    "url": "02-功能设计/01-用户与交互/设置项设计.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "设置项设计",
      "输入",
      "需求"
    ],
    "summary": "整理用户能配置什么、默认值是什么、设置会影响哪些模块。"
  },
  {
    "title": "交互流程",
    "url": "02-功能设计/01-用户与交互/交互流程.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "交互流程",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "用流程描述用户点击后的体验，避免只从代码函数角度设计。"
  },
  {
    "title": "异常状态",
    "url": "02-功能设计/01-用户与交互/异常状态.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "异常状态",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "提前设计失败、空数据、权限、配置错误等状态。"
  },
  {
    "title": "功能验收标准",
    "url": "02-功能设计/01-用户与交互/功能验收标准.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "功能验收标准",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "每个功能做完后用什么标准判断真的完成。"
  },
  {
    "title": "功能清单迁移",
    "url": "02-功能设计/00-功能全景/功能清单迁移.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Think OS 功能清单",
      "Timer",
      "app",
      "core",
      "docs/功能清单.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能清单迁移",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本文档记录项目当前已实现的功能，作为需求管理的基线参考。最后更新：2026-02-28位于 `scripts/*gate*.mjs`，包括：根据 `docs/计划.md` 最新状态：1. **Typecheck**：有 1 个 TS error"
  },
  {
    "title": "旧产品功能地图",
    "url": "02-功能设计/00-功能全景/旧产品功能地图.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-02-产品功能地图.js",
      "platform",
      "share",
      "二、产品功能地图",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "旧产品功能地图",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "按你的主线：记录 → 数据处理 → 展示"
  },
  {
    "title": "View UI 触发动作梳理",
    "url": "02-功能设计/02-ViewUI与移动端/ViewUI触发动作梳理.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "View UI 触发动作梳理",
      "View UI 触发动作梳理表 v1",
      "app",
      "core",
      "docs/VIEW_UI_TRIGGER_ACTIONS_V1.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "说明：本表只做盘点和语义归类，不改 UI 代码。覆盖范围：这两个入口最接近你想要的统一模型：它们的问题不是“不能用”，而是：真正的 UI 触发点不是 `core/utils/timelineInteraction.ts`，而是：Batch 2 完成后，这条链已经比较干净："
  },
  {
    "title": "移动端 UI 全量重构方案",
    "url": "02-功能设计/02-ViewUI与移动端/移动端UI全量重构方案.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/完整移动端 UI 重构方案.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "移动端 UI 全量重构方案",
      "移动端 UI 全量重构方案（地毯式覆盖版）",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本次重构的目标不是“把桌面端界面缩到手机里”，而是为移动端建立一套独立、完整、可维护的 UI 体系。当前移动端问题不是单点 bug，而是系统性缺陷：移动端 UI 重构必须遵循以下原则：1. **移动端独立建模**2. **共享业务，不共享壳层**"
  },
  {
    "title": "QuickInput 保存计划一致性",
    "url": "02-功能设计/03-QuickInput功能收口/QuickInput保存计划一致性.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 保存计划一致性",
      "QuickInput 保存计划一致性收口",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-output-plan-submit-consistency.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "上一阶段已经在编辑面板里做了“保存位置实时预览”，但实际保存时 usecase 仍会重新计算一次 OutputPlan / PersistencePlan。如果两边计算结果漂移，就可能出现：这类问题比普通失败更危险，所以本次加入提交前一致性校验。"
  },
  {
    "title": "QuickInput 迁移保存反馈",
    "url": "02-功能设计/03-QuickInput功能收口/QuickInput迁移保存反馈.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 迁移保存反馈",
      "QuickInput 迁移保存反馈收口",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-partial-success-and-migration-feedback.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "上一阶段已经允许路径变化时执行安全迁移保存：先写入新位置，再删除旧记录。但如果旧记录删除失败，结果是 `partial_success`，此前 UI 会把它当普通失败处理，容易造成两个问题：1. 用户以为没有保存成功，可能再次点击保存，制造重复记录。"
  },
  {
    "title": "QuickInput 路径变化保存策略",
    "url": "02-功能设计/03-QuickInput功能收口/QuickInput路径变化保存策略.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 路径变化保存策略",
      "QuickInput 路径变化保存策略更新",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-safe-mvp-change-note.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能设计",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "早期安全 MVP 对编辑时的目标路径变化采取“一律阻止保存”。这个策略能避免误迁移，但实际使用中过于保守：当用户确实切换了主题/模板并希望记录跟随新目标位置保存时，会被拦住。当前策略改为安全迁移保存：1. 目标路径不变：原地更新。2. 目标路径变化：先写入新位置，再删除旧记录。"
  },
  {
    "title": "技术总览",
    "url": "03-技术文档/00-技术全景/技术总览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术总览",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "从架构层面说明代码如何组织，文件地图是本主题的核心入口。"
  },
  {
    "title": "文件地图",
    "url": "03-技术文档/00-技术全景/文件地图.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "文件地图",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "技术文档的核心页：告诉你哪个文件夹负责什么，改功能先看哪里。"
  },
  {
    "title": "模块职责",
    "url": "03-技术文档/00-技术全景/模块职责.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "模块职责",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "定义模块负责什么、不负责什么，防止代码职责漂移。"
  },
  {
    "title": "插件生命周期",
    "url": "03-技术文档/00-技术全景/插件生命周期.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "插件生命周期",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "解释插件从加载到卸载发生了什么。"
  },
  {
    "title": "数据流",
    "url": "03-技术文档/04-运行机制/数据流.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "数据流",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "说明数据从 Obsidian Vault、设置、输入和服务之间如何流动。"
  },
  {
    "title": "事件流",
    "url": "03-技术文档/04-运行机制/事件流.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "事件流",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "记录 Obsidian 事件、用户事件和内部事件如何进入系统。"
  },
  {
    "title": "Obsidian API 使用",
    "url": "03-技术文档/04-运行机制/Obsidian API 使用.html",
    "tags": [
      "Obsidian",
      "Obsidian API 使用",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "集中说明 Obsidian API 应该从哪里被调用，以及如何隔离宿主依赖。"
  },
  {
    "title": "样式系统",
    "url": "03-技术文档/04-运行机制/样式系统.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "样式系统",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "说明插件样式从哪里来，如何避免样式散乱和互相污染。"
  },
  {
    "title": "构建流程",
    "url": "03-技术文档/04-运行机制/构建流程.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "构建流程",
      "架构",
      "测试",
      "移动端",
      "输入",
      "需求"
    ],
    "summary": "说明从源码到 Obsidian 可加载文件之间的构建和检查链路。"
  },
  {
    "title": "开发指南迁移",
    "url": "03-技术文档/01-架构导览/开发指南迁移.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/开发指南.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "开发指南",
      "开发指南迁移",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本文面向“要在本仓库继续开发/迭代功能的人”，目标是：新同学能在 30 分钟内跑起来、能定位代码入口、能通过质量门禁（gate）。安装依赖：如果 `npm run check` 失败，通常是触发了 `scripts/*gate*.mjs` 的边界约束；先看报错提示对应哪条 gate。"
  },
  {
    "title": "开发规范迁移",
    "url": "03-技术文档/01-架构导览/开发规范迁移.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/开发规范.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "开发规范迁移",
      "开发规范（可执行）",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "🔴 **必须遵守** - 违反会导致构建失败或严重问题🟡 **强烈建议** - 违反会影响代码质量或可维护性🟢 **最佳实践** - 长期遵守可提升开发体验1. **入口文件**：`src/main.ts`（插件启动点）2. **构建命令**：`npm run build`（生成 `main.js`/`styles.c"
  },
  {
    "title": "代码架构图总览",
    "url": "03-技术文档/01-架构导览/代码架构图总览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/总览.html",
      "platform",
      "share",
      "代码",
      "代码架构图总览",
      "写回",
      "发布",
      "回滚",
      "字段",
      "左边看“它像店里的什么地方”，右边看“它到底干嘛”",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明左边看“它像店里的什么地方”，右边看“它到底干嘛”这版不再用一堆积木块解释。左边是通俗导览列表，右边是列表式说明。每个文件夹都先用比喻帮你建立感觉，再用很短的话讲清楚：它在哪一层、干什么、和谁关系最近。项目导览看左边先建立感觉：它像什么。再看右边理解它具体做什么。"
  },
  {
    "title": "app 目录导览",
    "url": "03-技术文档/02-目录地图/app目录导览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "app 目录导览",
      "core",
      "features",
      "html/app.html",
      "platform",
      "share",
      "代码",
      "先把 app/ 看懂：它像店长办公室",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明先把 app/ 看懂：它像店长办公室这次不再讲整个项目，而是只讲app/。因为你现在最需要搞懂的，不是全部目录，而是app 到底管什么、和 core 有什么区别、里面每个子目录分别干嘛。你可以把 app 理解成：店已经开了，店长办公室开始安排今天怎么运转"
  },
  {
    "title": "core 目录导览",
    "url": "03-技术文档/02-目录地图/core目录导览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "core 目录导览",
      "features",
      "html/core.html",
      "platform",
      "share",
      "代码",
      "先把 app/ 看懂：它像店长办公室",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明先把 app/ 看懂：它像店长办公室这次不再讲整个项目，而是只讲app/。因为你现在最需要搞懂的，不是全部目录，而是app 到底管什么、和 core 有什么区别、里面每个子目录分别干嘛。你可以把 app 理解成：店已经开了，店长办公室开始安排今天怎么运转"
  },
  {
    "title": "features 目录导览",
    "url": "03-技术文档/02-目录地图/features目录导览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "features 目录导览",
      "html/features.html",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "继续把 features/ 看懂：它像店里顾客真正接触到的服务区",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明继续把 features/ 看懂：它像店里顾客真正接触到的服务区这次只讲features/。如果说core是后仓，app是店长办公室，那features就是顾客真正会走进去、会点击、会使用的那些服务区。你以后整理文件夹时，最关键的问题就是："
  },
  {
    "title": "platform 目录导览",
    "url": "03-技术文档/02-目录地图/platform目录导览.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/platform.html",
      "platform",
      "platform 目录导览",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "继续把 platform/ 看懂：它像店和外部环境的对接窗口",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明继续把 platform/ 看懂：它像店和外部环境的对接窗口这次只讲platform/。你可以把它理解成：店里和商场物业、门禁、电表、广播系统打交道的对接窗口。它不是顾客服务区，也不是后仓基础能力本身，而是负责把Obsidian"
  },
  {
    "title": "share 目录导览",
    "url": "03-技术文档/02-目录地图/share目录导览.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/share.html",
      "platform",
      "share",
      "share 目录导览",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "继续把 shared/ 看懂：它像店里的公共工具柜",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "代码架构图：左流程右说明继续把 shared/ 看懂：它像店里的公共工具柜这次只讲shared/。这是你以后整理文件夹时特别容易纠结的一层，因为很多项目最后都会把 shared 用成“杂物间”。你可以把它理解成：店里多个区域都会来借东西的公共工具柜"
  },
  {
    "title": "旧代码架构图",
    "url": "03-技术文档/01-架构导览/旧代码架构图.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-04-代码架构图.js",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "四、代码架构图",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "旧代码架构图",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "直接在图区域缩放与横移"
  },
  {
    "title": "架构视角逐文件",
    "url": "03-技术文档/03-代码视角/架构视角逐文件.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-05-架构视角逐文件.js",
      "platform",
      "share",
      "五、架构视角（逐文件）",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "架构视角逐文件",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "看装配、边界、共享、生命周期"
  },
  {
    "title": "领域视角逐文件",
    "url": "03-技术文档/03-代码视角/领域视角逐文件.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-06-领域视角逐文件.js",
      "platform",
      "share",
      "代码",
      "六、领域视角（逐文件）",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求",
      "领域视角逐文件"
    ],
    "summary": "看概念、规则、状态迁移"
  },
  {
    "title": "业务视角逐文件",
    "url": "03-技术文档/03-代码视角/业务视角逐文件.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-07-业务视角逐文件.js",
      "platform",
      "share",
      "七、业务视角（逐文件）",
      "业务视角逐文件",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "看用户入口和闭环"
  },
  {
    "title": "数据流与流程图",
    "url": "03-技术文档/04-运行机制/数据流与流程图.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "html/thinkos-章节化文档框架/chapter-08-数据流与流程图.js",
      "platform",
      "share",
      "代码",
      "八、数据流与流程图",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "数据流与流程图",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "图在当前区域缩放和横移"
  },
  {
    "title": "字段系统重构方案",
    "url": "03-技术文档/05-字段与输入/字段系统重构方案.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/字段重构方案.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "字段系统深度审计报告与重构方案（架构 / 领域 / 表单 / 上下文 / 筛选全覆盖）",
      "字段系统重构方案",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本报告不是单纯讨论“字段类型有哪些”，而是把字段当成插件的核心骨架进行审视。字段在当前插件中不是一个 UI 细节，而是贯穿全链路的主轴：因此，字段系统如果没有被当成“一级架构对象”来设计，插件后续一定会不断出现：但我不建议“整仓推翻重来”，而建议："
  },
  {
    "title": "统一输入现状盘点",
    "url": "03-技术文档/05-字段与输入/统一输入现状盘点.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "docs/收集.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "统一输入改造 · 第 1 轮现状盘点报告（只做“看清”）",
      "统一输入现状盘点",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "目标：完成 5 张表的第一版——**写入口清单、UseCase 清单、校验/补全清单、副作用清单、竞态热点清单**。范围：基于上传代码包中与下列目录直接相关的实现进行静态盘点：这类报告里，“详尽”不是把文件名堆满，而是至少满足这 5 条：1. **覆盖够广**：你指定的关键目录都看过，而且不是只看文件名，而是能说明“谁"
  },
  {
    "title": "QuickInput 多步推进 Snapshot",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInput多步推进Snapshot.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 多步推进 Snapshot",
      "QuickInput 多步推进：任务内容单入口、时间计算别名、Snapshot 主链准备",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-multi-step-task-time-snapshot.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "这一步不是单个 bugfix，而是把前面几个主线点合并推进：1. **任务编辑初始值更靠近 Snapshot**：`editStateResolver.buildInitialFormData()` 先构造 `ParsedRecordSnapshot`，字段回填优先读 `snapshot.semantic`。"
  },
  {
    "title": "QuickInput Legacy 调试收口",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInputLegacy调试收口.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "QuickInput Legacy 调试收口",
      "QuickInput 主线收口：Legacy 与调试入口整理",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-legacy-closeout-and-debug.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本次不删除大块旧逻辑，避免引入新风险；重点是把主路径继续向 snapshot 收拢，并把调试入口统一。新增：统一使用：开启方式：这样 parser、编辑回填、保存前时间计算不再各自散落 `console.log` 判断。`editStateResolver.ts` 中，`buildInitialFormData()`"
  },
  {
    "title": "QuickInput 任务内容提取调试",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInput任务内容提取调试.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 任务内容提取调试",
      "QuickInput 任务内容提取调试说明",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-task-content-extraction-debug.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "示例任务：真正的内容应该是：这次重新审视后，结论是：任务内容不能再从 `title` 取，也不能按空格 split。正确方式应该是从原始任务行中剥离任务语法、开头图标、元数据、tag 后，保留中间整段正文。1. `stripTaskLineToEditableText()` 只剥离任务语法和元数据，不压缩正文内部连续空"
  },
  {
    "title": "QuickInput 任务内容单一入口",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInput任务内容单一入口.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 任务内容单一入口",
      "QuickInput 任务内容提取单一入口",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-task-content-single-entry.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本次属于主线 P7 + P8：重新收敛任务内容提取方法。之前的问题是：所以这次把任务正文提取统一到一个入口：`extractTaskEditableText()` 位于：它负责：1. 去掉任务前缀：`- [ ]` / `- [x]`2. 去掉开头图标：例如 `🖥`"
  },
  {
    "title": "QuickInput 任务模板护栏",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInput任务模板护栏.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 任务模板护栏",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-task-template-guard.md",
      "features",
      "platform",
      "share",
      "代码",
      "任务编辑模板类型护栏修复",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "用户编辑任务时，原任务行包含：之前编辑链路只把 `templateId` 当成 blockId 查找。当 `ovr_xxx` 是主题覆盖模板 ID 时，直接查 block 会失败，随后进入启发式打分。如果「闪念」这类 block 模板打分更高，就会把任务误读成 block/闪念，导致 OutputPlan 计算出从任务"
  },
  {
    "title": "QuickInput 任务写回保真",
    "url": "03-技术文档/06-QuickInput技术记录/QuickInput任务写回保真.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 任务写回保真",
      "QuickInput 任务写回保真补丁说明",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-task-writeback-preservation.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术文档",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本次是主线计划中的 P7：任务写回保真。目标不是做跨文件迁移，也不是完全重写 task patch serializer，而是在当前“模板渲染后原地替换”的基础上，加一层安全保护，避免编辑任务时把原任务行里的未知上下文直接丢掉。当前任务编辑保存链路仍然是："
  },
  {
    "title": "需求评审",
    "url": "04-评审中心/00-评审方法/需求评审.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求",
      "需求评审"
    ],
    "summary": "判断需求是否值得做、是否足够清楚、是否能验收。"
  },
  {
    "title": "功能评审",
    "url": "04-评审中心/00-评审方法/功能评审.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "功能评审",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求"
    ],
    "summary": "判断功能设计是否完整，是否能给用户带来明确价值。"
  },
  {
    "title": "技术方案评审",
    "url": "04-评审中心/00-评审方法/技术方案评审.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "技术方案评审",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求"
    ],
    "summary": "判断技术方案是否合理、复杂度是否可控、有没有更简单方案。"
  },
  {
    "title": "代码结构评审",
    "url": "04-评审中心/01-质量评审/代码结构评审.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "代码结构评审",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求"
    ],
    "summary": "判断代码结构是否健康，是否会让未来维护变难。"
  },
  {
    "title": "发布评审",
    "url": "04-评审中心/01-质量评审/发布评审.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "发布评审",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求"
    ],
    "summary": "发布前判断是否可以交付，是否需要延后或回滚准备。"
  },
  {
    "title": "风险评审",
    "url": "04-评审中心/01-质量评审/风险评审.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求",
      "风险评审"
    ],
    "summary": "判断当前改动可能带来的技术、数据、体验和发布风险。"
  },
  {
    "title": "字段系统深度评审",
    "url": "04-评审中心/02-专题评审/字段系统深度评审.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "字段系统深度评审",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "需求"
    ],
    "summary": "把字段系统重构方案作为评审对象，判断是否值得实施、如何分阶段落地。"
  },
  {
    "title": "QuickInput 调试与 Legacy 规范",
    "url": "04-评审中心/02-专题评审/QuickInput调试与Legacy规范.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 调试与 Legacy 注释规范",
      "QuickInput 调试与 Legacy 规范",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-debug-and-legacy-notes.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "评审中心",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "任务读取和时间计算相关调试统一通过：关闭：新增日志必须满足：如果保留旧链路 fallback，必须写清楚：禁止没有退出条件的长期双轨。"
  },
  {
    "title": "测试清单",
    "url": "05-维护发布/00-测试验收/测试清单.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "测试清单",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "把测试从临时想起来变成固定动作。"
  },
  {
    "title": "发布流程",
    "url": "05-维护发布/01-发布与回滚/发布流程.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "发布流程",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "发布前后按固定流程检查，避免漏步骤。"
  },
  {
    "title": "Changelog",
    "url": "05-维护发布/01-发布与回滚/Changelog.html",
    "tags": [
      "Changelog",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "记录面向未来的变更历史。"
  },
  {
    "title": "Bug 处理流程",
    "url": "05-维护发布/01-发布与回滚/Bug处理流程.html",
    "tags": [
      "AI",
      "Bug 处理流程",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "记录 bug 从发现到修复的标准路径。"
  },
  {
    "title": "兼容性记录",
    "url": "05-维护发布/01-发布与回滚/兼容性记录.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "Timer",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "兼容性记录",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "记录插件对 Obsidian、桌面端/移动端、依赖版本的兼容情况。"
  },
  {
    "title": "回滚方案",
    "url": "05-维护发布/01-发布与回滚/回滚方案.html",
    "tags": [
      "AI",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "回滚方案",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "需求"
    ],
    "summary": "当发布或迁移出问题时，明确怎么恢复。"
  },
  {
    "title": "测试方案迁移",
    "url": "05-维护发布/00-测试验收/测试方案迁移.html",
    "tags": [
      "AI",
      "DataStore",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/测试方案.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "测试方案迁移",
      "移动端",
      "维护发布",
      "表 1：按阶段/事项的测试策略（从“用户体验”到“底层 gate”）",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "好，我明白你要的东西了：**不是原则，不是模板，而是“结合你这张计划表和现在代码的真实状态，给一份可以直接开干的测试计划”，而且要是表格，从上到下。**下面这份我按你现在的阶段表来设计，重点偏 **端到端**，然后才是集成/单测和 gate。你可以直接按表里的“建议动作”一条条做。"
  },
  {
    "title": "QuickInput 主线验收清单",
    "url": "05-维护发布/00-测试验收/QuickInput主线验收清单.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 主线验收清单",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-acceptance-checklist.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "从旧 docs/html 迁移来的文档，已按新文档结构重新归类。"
  },
  {
    "title": "QuickInput 最终验收清单",
    "url": "05-维护发布/00-测试验收/QuickInput最终验收清单.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 最终验收清单",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-final-acceptance.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "本清单用于确认 QuickInput 本轮主线修改已经收口。重点不是继续扩功能，而是确认：任务读得准、时间算得准、写回不误伤、迁移保存可追踪。原始任务：验收：验收：验收：验收：主题 `工作/设计/道旗` 应拆出：视图设置中应能使用这三个字段筛选或展示。"
  },
  {
    "title": "QuickInput 风险与回滚说明",
    "url": "05-维护发布/01-发布与回滚/QuickInput风险与回滚说明.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 风险与回滚说明",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-risk-and-rollback.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "当前策略是：1. 先写入新位置2. 再删除旧记录3. 删除失败则返回 partial_success风险：回滚方式：风险：回滚方式：风险：回滚方式：风险：处理原则：如果线上出现严重问题，按这个顺序回滚：1. 关闭迁移保存，恢复为路径变化阻止2. 保留任务读取修复"
  },
  {
    "title": "QuickInput 构建导出修复",
    "url": "05-维护发布/02-修复记录/QuickInput构建导出修复.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 构建导出修复",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-build-export-fix.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "构建时报错：原因是 `QuickInputModal.tsx` 从 `@core/public` 引入了 `buildRecordSubmitFeedbackPresentation`，但当前源码中的 `core/utils/recordSubmitFeedback.ts` 没有实现这个函数，`core/public."
  },
  {
    "title": "Block Statistics 统一与跳转修复",
    "url": "05-维护发布/02-修复记录/BlockStatistics统一与跳转修复.html",
    "tags": [
      "AI",
      "Block Statistics 统一与跳转修复",
      "Obsidian",
      "QuickInput",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/本次改动-block-statistics-md统一与跳转修复.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "本次改动：Block / Statistics Markdown 统一与跳转修复",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "`LayoutRenderer -> StatisticsViewContainer -> PopoverContent -> BlockView -> BlockItem -> MarkdownContent -> ObsidianMessageRenderPort`"
  },
  {
    "title": "QuickInput 任务正文空格保留修复",
    "url": "05-维护发布/02-修复记录/QuickInput任务正文空格保留修复.html",
    "tags": [
      "Obsidian",
      "QuickInput",
      "QuickInput 任务正文空格保留修复",
      "Snapshot",
      "Think OS",
      "app",
      "core",
      "docs/quickinput-task-editable-text-space-preservation.md",
      "features",
      "platform",
      "share",
      "代码",
      "写回",
      "发布",
      "回滚",
      "字段",
      "插件文档",
      "架构",
      "测试",
      "移动端",
      "维护发布",
      "输入",
      "迁移",
      "需求"
    ],
    "summary": "示例任务：期望正文是：这里 `长治学院` 和 `设计道旗定稿` 中间有两个空格，属于用户输入内容。旧的正文清理逻辑最后使用 `/\\s+/g` 把所有连续空白压成一个空格，导致编辑回填时看起来像正文没有被完整读取。修改文件：`stripTaskLineToEditableText()` 仍然会移除："
  }
];
